# Generated by Django 4.2.3 on 2023-07-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=50, unique=True)),
                ('chapter_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_serial', models.IntegerField()),
                ('level_letters', models.CharField(max_length=50)),
                ('level_completed', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordapp.chapter')),
            ],
            options={
                'unique_together': {('level_letters', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_word', models.CharField(max_length=50)),
                ('solution_details', models.TextField(default=None, max_length=1000, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordapp.level')),
            ],
        ),
    ]
