# Generated by Django 4.2.3 on 2023-07-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0002_alter_chapter_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='level',
            name='level_completed',
            field=models.BooleanField(default=False),
        ),
    ]
