# Generated by Django 4.2.3 on 2023-07-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0003_chapter_chapter_completed_level_level_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='solution_details',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
    ]
